name: innova_service
description: A new Flutter application.

dependencies:
  flutter:
    sdk: flutter



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  # To use call and email
  url_launcher:

  # To use camera in the app
  image_picker:

  # To send photo
  mailer3:

  #to use Whatsapp
  flutter_launch:

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - asset/images/home_bg.png
    - asset/images/logo.png
    - asset/images/whatsapp_logo.png
    - asset/images/page_1_av.png
    - asset/images/page_1_bg.png
    - asset/images/page_2_av.png
    - asset/images/page_2_bg.jpeg
    - asset/images/page_3_av.png
    - asset/images/page_3_bg.jpg
    - asset/images/page_4_av.png
    - asset/images/page_4_bg.jpg
    - asset/images/page_5_av.png
    - asset/images/page_5_bg.png
    - asset/images/facebook.png
    - asset/images/letter.png
    - asset/images/phone.png
    - asset/images/whatsapp.png
    - asset/images/worldwide.png
    - asset/images/facebook_logo_button.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: Montserrat
       fonts:
         - asset: asset/fonts/Montserrat-Regular.ttf
         - asset: asset/fonts/Montserrat-Bold.ttf
         - asset: asset/fonts/Montserrat-Light.ttf

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
